### PR TITLE
Plot functions for Cortes et al

### PR DESCRIPTION
**Pull request by nicolepcortes**
## Changes proposed in this PR:
- Added Functions needed to recreate plots
- Included notebook with examples and details on how to make each plot and a script to create and save each plot in the manuscript

### Legal Acknowledgement

By contributing to this software project, I agree to the following terms and conditions for my
contribution:

1. I agree my contributions are submitted under the license terms described in the LICENSE.txt file
   at the top level of this directory.
2. I represent I am authorized to make the contributions and grant the license. If my employer has
   rights to intellectual property that includes these contributions, I represent that I have
   received permission to make contributions and grant the required license on behalf of that
   employer.

### CODE REVIEW

**Comment by ksbeattie** [comment]
@nicolepcortes is this ready to merge now?

**Comment by adowling2** [comment]
Manuscript is in revision

**Comment by ksbeattie** [comment]
Still in revision?

**Comment by adowling2** [comment]
We should merge this into a branch on the repo (not main) for archiving. All/most of the plots for this manuscript were remade. I think this branch was not used for the final version of the paper.

**Comment by ksbeattie** [comment]
> We should merge this into a branch on the repo (not main) for archiving. All/most of the plots for this manuscript were remade. I think this branch was not used for the final version of the paper.

@nicolepcortes is that something you can do?  Either update the plots used in the manuscript and merge to main, or merge this to a branch?

**Comment by djlaky** [comment]
@ksbeattie We can close this pull request as it has been updated in #16. #16 should be ready to go.

**Pull request closed without merging**
